apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  labels: { app: vault }
spec:
  serviceName: "vault"
  replicas: 1
  selector:
    matchLabels: { app: vault }
  template:
    metadata:
      labels: { app: vault }
    spec:
      containers:
        - name: vault
          image: default-route-openshift-image-registry.apps.rm3.7wse.p1.openshiftapps.com/hammadmaqsood135-dev/vault:1.17
          imagePullPolicy: IfNotPresent
          args: ["server", "-config=/vault/config/vault.hcl"]
          ports:
            - containerPort: 8200
              name: http
          env:
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"
          volumeMounts:
            - name: config
              mountPath: /vault/config
            - name: data
              mountPath: /vault/data
      volumes:
        - name: config
          configMap:
            name: vault-config
        - name: data
          emptyDir: { }
#  volumeClaimTemplates:
#    - metadata:
#        name: data
#      spec:
#        accessModes: ["ReadWriteOnce"]
#        resources:
#          requests:
#            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  labels: { app: vault }
spec:
  selector: { app: vault }
  ports:
    - name: http
      port: 8200
      targetPort: 8200
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vault
  labels: { app: vault }
spec:
  to:
    kind: Service
    name: vault
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect